feat: Use perfect hash tables for file types and icons
ogham/exa pull request #1229
Opened 2023-08-04 22:49 UTC by cfxegbert

Change filetype and icon lookup to use perfect hash tables to simplify lookups.

- Perfect hash maps are generated at compile instead of runtime avoiding the lazy_static initialization of MAP_BY_NAME.
- Perfect hash maps are sized to the data and do not need to allocate extra buckets that a regular hash map creates.
- Avoid the linear searches for the file extensions in both the filetype and icon.  Match statements of str does a linear walk of each pattern.
- Remove the coupling between icon and filetype.  This will allow a more specific icon to be used instead of the generic icon for filetype.  For example, a file with an svg extension can use the filetype color for an image but use an icon to shows it is vector art instead of a bitmap image.  As a result of removing the coupling all the filetypes for image, video, music, and lossless had to be added to the icon map.  Most of them were already in the icon map.
- Create constants for a majority of unicode icons. 
- Fix icons removed in Nerd Fonts 3.x

2023-08-05 01:22 UTC, cfxegbert commented
Added pull request #1221

2023-08-26 21:38 UTC, cfxegbert commented
Added pull request #1194 #1191 #1162 #1150 #1148 #1144 #1140 #1120 #1100 #1238 #1234

2023-08-27 06:34 UTC, cfxegbert commented
Matched icons with https://github.com/eza-community/eza

2023-09-01 13:22 UTC, cafkafk requested changes

2023-09-01 13:22 UTC, cafkafk commented on src/info/filetype.rs
> +    fn get_file_type(file: &File<'_>) -> Option<FileType> {
This should have some doc comments

2023-09-01 13:22 UTC, cafkafk commented on build.rs
> +/// Create the perfect hashing for file icons
I think you should expand on this, how it's done and the motivation for doing it this way.

2023-09-01 13:22 UTC, cafkafk commented on build.rs
> +fn generate_directory_icon_map(file: &mut File) -> io::Result<()> {
This should have some doc comments

2023-09-01 13:22 UTC, cafkafk commented
ohh wrong pr

2023-09-06 15:13 UTC, closed without merging

2023-09-06 15:13 UTC, ariasuni commented
exa is unmaintained, and this has been merged in [the active fork eza](https://github.com/eza-community/eza), so I see no reason to keep this PR around (thanks a lot for the effort though). Also see https://github.com/ogham/exa/issues/1243