feat: New Icons and CLI argument to suppress icons
ogham/exa pull request #759
Opened 2020-10-30 22:10 UTC by stuartcarnie

This PR introduces two improvements:

* a significant number of new icons and includes a comment showing the character to which the extension or file maps to
* A new switch, `--no-icons` to explicitly hide icons, which takes precedence over `--icons`. This switch is useful when using aliases and which to temporarily hide the icons

2020-11-04 16:59 UTC, timbedard commented
Oh heck yeah. I was thinking that some of these icons were missing.

2020-11-04 18:07 UTC, timbedard requested changes

2020-11-04 18:07 UTC, timbedard commented on src/output/icons.rs
> +        m.insert("dockerfile", '\u{f308}'); // 
`Dockerfile` is the conventional file name.
```suggestion
        m.insert("Dockerfile", '\u{f308}'); // 
```

2020-12-29 18:08 UTC, ariasuni requested changes
I think it’s great. Here what’s missing:

- You should add this flag to the fish completion file too.
- You should add the option to the README.
- You should add the option to the man page.

2021-02-27 20:49 UTC, stuartcarnie commented
Hi @ariasuni and thank you for the feedback! I've completed all the suggestions.

2021-03-29 22:09 UTC, ogham commented
Thanks!

I don't actually use icons myself (I just never got into using them) which is why they always seem to be lagging behind, missing, etc.

2021-03-29 22:09 UTC, merged