Add support for querying timezone on Android
ogham/exa pull request #846
Opened 2021-04-14 12:38 UTC by skyline75489

2021-04-14 12:39 UTC, skyline75489 commented
OK the code does *not* work. The compiler complains:

```text
error[E0283]: type annotations needed
   --> src/output/table.rs:324:20
    |
324 |             return CompiledData::parse(output.stdout);
    |                    ^^^^^^^^^^^^^^^^^^^ cannot infer type
    |
    = note: cannot satisfy `_: CompiledData`
    = note: required by `zoneinfo_compiled::CompiledData::parse`

error: aborting due to previous error; 1 warning emitted
```

But I honestly don't know what's wrong with it.

2021-05-08 15:09 UTC, ariasuni requested changes

2021-05-08 15:09 UTC, ariasuni commented on src/output/table.rs
> +        if env::consts::OS == "android" {
I suppose it’s a good practice to include the “documentation” for this change.

```suggestion
        /// https://android.googlesource.com/platform/bionic/+/master/libc/tzcode/bionic.cpp
        if env::consts::OS == "android" {
```

2021-05-08 15:33 UTC, ariasuni commented
Well actually your approach is wrong. `persist.sys.timezone` doesn’t contain the data to parse but I guess the filename relative to the directory containing the `TZDATA`, and Bionic’s source code seems to also take into account the «first format» described at https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html.

I’m really starting to think we should stop trying to replace the `libc` and use standard C function so that compatibility with OS isn’t such a nightmare of trying to understand what such or such libc are actually doing.

2021-05-11 00:47 UTC, skyline75489 commented
Closed in favor of #867

2021-05-11 00:47 UTC, closed without merging