Update lockfile
ogham/exa pull request #854
Opened 2021-04-22 14:41 UTC by harens

Hopefully closes https://github.com/ogham/exa/issues/853.

Update the lockfile to match `cargo.toml`.

2021-04-26 16:58 UTC, ariasuni commented
Please update Rust’s version to 1.45.0 in `.travis.yml` and `README.md`, like I did in [#857](https://github.com/ogham/exa/pull/857/files). You updated the `git2` version, and now it needs at least Rust 1.45.0.

2021-04-26 17:42 UTC, harens commented
Thank you for your response @ariasuni (and for your work on this project).

I left it as a separate commit so as not to get too much in the way of #857, and so that it's possible to only cherry pick my original commit if desired.

2021-04-26 17:45 UTC, ariasuni commented
Don’t worry, I’ll rebase my pull request after I merge this. I’m just waiting for the CI checks to finish.

2021-04-26 21:26 UTC, ariasuni requested changes
Let’s depend on Rust 1.45.2 since it the latest 1.45.x and it fixes bugs. Also, the link to the Rust blog was incorrect.

2021-04-26 21:26 UTC, ariasuni commented on README.md
> +    <img src="https://img.shields.io/badge/rustc-1.45+-lightgray.svg" alt="Rust 1.45+" />
```suggestion
<a href="https://blog.rust-lang.org/2020/08/03/Rust-1.45.2.html">
    <img src="https://img.shields.io/badge/rustc-1.45.2+-lightgray.svg" alt="Rust 1.45.2+" />
```

2021-04-26 21:26 UTC, ariasuni commented on README.md
> +You will need rustc version 1.45.0 or higher.
```suggestion
You will need rustc version 1.45.2 or higher.
```

2021-04-26 21:26 UTC, ariasuni commented on .travis.yml
> +  - 1.45.0
```suggestion
  - 1.45.2
```

2021-04-26 21:37 UTC, merged

2021-04-26 21:39 UTC, ariasuni commented
Aaaand it’s done! \o/ Also:

> Thank you for your response @ariasuni (and for your work on this project).

I’m glad my work is useful and appreciated :)

2021-04-27 11:04 UTC, harens commented
Thank you for merging! 🎉 (and for correcting my mistakes...)